### ISSUE TITLE
Package size increased after obfuscate

### ISSUE THREAD

**Issue by JackyGohSG** [z0ffy/vite-plugin-bundle-obfuscator#106]
After running with vitePluginBundleObfuscator, it seems to increase the package size compared to not using it. Is there a way we can optimize it?

these are the plugins i'm running

plugins: [
    react(),
    nodePolyfills(),
    ViteImageOptimizer(),
    vitePluginBundleObfuscator({
      log: false,
      enable: true,
      autoExcludeNodeModules: true,
      threadPool: true,
    }),
  ],

**Comment by z0ffy** [comment]
> After running with vitePluginBundleObfuscator, it seems to increase the package size compared to not using it. Is there a way we can optimize it?
> 
> these are the plugins i'm running
> 
> plugins: [ react(), nodePolyfills(), ViteImageOptimizer(), vitePluginBundleObfuscator({ log: false, enable: true, autoExcludeNodeModules: true, threadPool: true, }), ],

Firstly, it can be determined that confusion will definitely increase the output size. However, there is no need to worry too much, as optimization can be achieved through the following two methods:

1. By configuring tools similar to [Terser](https://vite.dev/config/build-options.html#build-terseroptions) to reduce the size of the output before obfuscation.
2. The default obfuscation configuration has taken into account speed, size, and quality. If you are still not satisfied with the results, you can adjust the [obfuscation configuration](https://github.com/javascript-obfuscator/javascript-obfuscator?tab=readme-ov-file#javascript-obfuscator-options) yourself. (Reference configuration: controlFlowFlattening、 deadCodeInjection、 ...)

If you like this plugin, please give me a star, which will be my motivation for development.

Finally, if you have any other questions, please contact me in a timely manner.
