### ISSUE TITLE
Bundle non-obfuscated vendor modules with main bundled obfuscated file

### ISSUE THREAD

**Issue by DukeVen** [z0ffy/vite-plugin-bundle-obfuscator#116]
Currently, the obfuscator outputs 2 files when autoExcludeNodeModules enabled, main.js and vendor-modules.js.
Would it possible to bundle the non-obfuscated vendor/node-modules with the main bundled obfuscated file? So that in the end you have 1 file where vendor-modules and the main file are merged, but without vendor-modules also being obfuscated.

**Comment by z0ffy** [comment]
> Currently, the obfuscator outputs 2 files when autoExcludeNodeModules enabled, main.js and vendor-modules.js. Would it possible to bundle the non-obfuscated vendor/node-modules with the main bundled obfuscated file? So that in the end you have 1 file where vendor-modules and the main file are merged, but without vendor-modules also being obfuscated.

Thank you for your attention to this plugin. It is very regrettable currently it is not possible to achieve. I have noticed this scene and will continue to follow up.
