### ISSUE TITLE
新版本好像依然不支持

### ISSUE THREAD

**Issue by setube** [z0ffy/vite-plugin-bundle-obfuscator#27]
![Clip_2024-09-11_17-13-28](https://github.com/user-attachments/assets/de27ba0b-10f9-4c47-8875-bf60cd5003a1)

**Comment by z0ffy** [comment]
> ![Clip_2024-09-11_17-13-28](https://private-user-images.githubusercontent.com/73606411/366384230-de27ba0b-10f9-4c47-8875-bf60cd5003a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDczMjIsIm5iZiI6MTcyNjA0NzAyMiwicGF0aCI6Ii83MzYwNjQxMS8zNjYzODQyMzAtZGUyN2JhMGItMTBmOS00YzQ3LTg4NzUtYmY2MGNkNTAwM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA5MzAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1Yjc5ZTEwMjU0MmUyOWY3MGE4MjdiMDYwZTQ4M2UyZGEwYTBhNTk3Y2NlNDFhZDQ4NjkwYmUzMjk5M2EwOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3b82uD5e9DiI0bINcP1PQyusIgOmsxdLzAa6Vm_apR4)

目前还在找解决方法，等我搞定了，跟你说

**Comment by z0ffy** [comment]
@setube 另外我想问一下，你会针对node_module进行拆包么

**Comment by setube** [comment]
> > ![Clip_2024-09-11_17-13-28](https://private-user-images.githubusercontent.com/73606411/366384230-de27ba0b-10f9-4c47-8875-bf60cd5003a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDczMjIsIm5iZiI6MTcyNjA0NzAyMiwicGF0aCI6Ii83MzYwNjQxMS8zNjYzODQyMzAtZGUyN2JhMGItMTBmOS00YzQ3LTg4NzUtYmY2MGNkNTAwM2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA5MzAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1Yjc5ZTEwMjU0MmUyOWY3MGE4MjdiMDYwZTQ4M2UyZGEwYTBhNTk3Y2NlNDFhZDQ4NjkwYmUzMjk5M2EwOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3b82uD5e9DiI0bINcP1PQyusIgOmsxdLzAa6Vm_apR4)
> 
> 目前还在找解决方法，等我搞定了，跟你说

你参考下https://github.com/elmeet/vite-plugin-javascript-obfuscator

**Comment by setube** [comment]
> @setube 另外我想问一下，你会针对node_module进行拆包么

不会hhh

**Comment by z0ffy** [comment]
> > @setube 另外我想问一下，你会针对node_module进行拆包么
> 
> 不会hhh

ok，我再想想，看看怎么搞合适点

**Comment by z0ffy** [comment]
@setube 试试最新的，加了一个参数 autoExcludeNodeModules

**Comment by setube** [comment]
新版本可以了 @z0ffy

**Comment by z0ffy** [comment]
> 新版本可以了 @z0ffy

那就点个star吧？🤝

**Comment by setube** [comment]
点了哦
