### ISSUE TITLE
请问支持路由懒加载混淆吗？

### ISSUE THREAD

**Issue by OVYVO** [z0ffy/vite-plugin-bundle-obfuscator#39]
老哥，路由懒加载不是按需引入各模块的js嘛，插件支持混淆动态加载的js模块文件不?

**Comment by z0ffy** [comment]
> 老哥，路由懒加载不是按需引入各模块的js嘛，插件支持混淆动态加载的js模块文件不?

支持，你试下

**Comment by OVYVO** [comment]
> > 老哥，路由懒加载不是按需引入各模块的js嘛，插件支持混淆动态加载的js模块文件不?
> 
> 支持，你试下

确实可以，感谢老哥
