### ISSUE TITLE
路由跳转其他页面的时候报错Uncaught (in promise) TypeError: _0x3cba47.map is not a function

### ISSUE THREAD

**Issue by Eastsea314** [z0ffy/vite-plugin-bundle-obfuscator#76]
![screenshot-20241107-160447](https://github.com/user-attachments/assets/0ce93ecb-3184-4f98-b34a-df44769a3ce3)

**Comment by z0ffy** [comment]
> ![screenshot-20241107-160447](https://private-user-images.githubusercontent.com/101165875/383867710-0ce93ecb-3184-4f98-b34a-df44769a3ce3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5Njc4NTMsIm5iZiI6MTczMDk2NzU1MywicGF0aCI6Ii8xMDExNjU4NzUvMzgzODY3NzEwLTBjZTkzZWNiLTMxODQtNGY5OC1iMzRhLWRmNDQ3NjlhM2NlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwODE5MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGE4ZDI0M2Y2YThlZmIxOWY0OTllMTdmNzdlODI2ODFkMWY3MzU2NGFiNzIwZmJlOWViZTQ3MjYyNTU2ODlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hP_WjN44H2OF9w1aN1nEgDqG1JC9kpGjcDDo5TktdYs)

看下 vite配置以及package.json

**Comment by Eastsea314** [comment]
`import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
// import VueDevTools from 'vite-plugin-vue-devtools'
import path from 'path'
import Components from 'unplugin-vue-components/vite';
import { VantResolver } from 'unplugin-vue-components/resolvers';
import { loadEnv } from "vite";
// import obfuscatorPlugin from "vite-plugin-javascript-obfuscator";
// import obfuscator from 'rollup-plugin-obfuscator';
import vitePluginBundleObfuscator from 'vite-plugin-bundle-obfuscator';

const defaultObfuscatorConfig:any = {
    excludes: [/vue-router/],
    enable: true,
    log: true,
    autoExcludeNodeModules: false,
    // autoExcludeNodeModules: { enable: true, manualChunks: ['vue'] },
    threadPool: false,
    // threadPool: { enable: true, size: 4 }
    options: {
        compact: true,
        controlFlowFlattening: true,
        controlFlowFlatteningThreshold: 1,
        deadCodeInjection: false,
        debugProtection: true,
        debugProtectionInterval: 0,
        disableConsoleOutput: false,
        identifierNamesGenerator: 'hexadecimal',
        log: false,
        numbersToExpressions: false,
        renameGlobals: false,
        selfDefending: true,
        simplify: true,
        splitStrings: false,
        stringArray: false,
        stringArrayCallsTransform: false,
        stringArrayCallsTransformThreshold: 0.5,
        stringArrayEncoding: [],
        stringArrayIndexShift: true,
        stringArrayRotate: true,
        stringArrayShuffle: true,
        stringArrayWrappersCount: 1,
        stringArrayWrappersChainedCalls: true,
        stringArrayWrappersParametersMaxCount: 2,
        stringArrayWrappersType: 'variable',
        stringArrayThreshold: 0.75,
        unicodeEscapeSequence: false,
    }
}
export default ({mode})=>{
    const env = loadEnv(mode, './')
    // console.log(env)
    return defineConfig({
        plugins: [
        // VueDevTools(),
        vue(),
        Components({
            resolvers: [VantResolver()],
        }),
        env.VITE_NODE_ENV==='development' ? null : 
        vitePluginBundleObfuscator(defaultObfuscatorConfig)      
        ],
        server:{
            host: "localhost",
        port: 8081,
            proxy: {
            '/h5Api': {
                // target: "https://gw-mmptest.myj.com.cn",
                target: env.VITE_APP_BASE_URL,
                ws: true,
                changeOrigin: true,
                rewrite: (path) => path.replace(/^\/h5Api/, ''),
                configure: (proxy, options) => {
                proxy.on('proxyReq', (proxyReq, req, res, options) => {
                    proxyReq.removeHeader('origin')
                    let proxyUrl = proxyReq.protocol + '//' + proxyReq.host + proxyReq.path
                    res.setHeader('real-proxy-url', proxyUrl)
                    // console.log(proxyUrl);
                })
                },
            },
            }
        },
        resolve: {
        alias: {
            '@': path.resolve(__dirname, 'src')
        }
        },
        build: {
        rollupOptions: {
            output: {
            chunkFileNames: 'static/js/[name]-[hash].js',
            entryFileNames: 'static/js/[name]-[hash].js',
            assetFileNames: 'static/[ext]/[name]-[hash].[ext]',
            }
        },
        minify:'terser',
        terserOptions: {
            compress: {
            drop_console: true,
            drop_debugger: true,
            },
        },
        },
    })
}

`




![screenshot-20241107-172212](https://github.com/user-attachments/assets/39f03d35-faaf-4528-b5e1-fdc5d334ee3f)

**Comment by z0ffy** [comment]
> ` import` { defineConfig } from 'vite' import vue from '@vitejs/plugin-vue' // import VueDevTools from 'vite-plugin-vue-devtools' import path from 'path' import Components from 'unplugin-vue-components/vite'; import { VantResolver } from 'unplugin-vue-components/resolvers'; import { loadEnv } from "vite"; // import obfuscatorPlugin from "vite-plugin-javascript-obfuscator"; // import obfuscator from 'rollup-plugin-obfuscator'; import vitePluginBundleObfuscator from 'vite-plugin-bundle-obfuscator';
> 
> const defaultObfuscatorConfig:any = { excludes: [/vue-router/], enable: true, log: true, autoExcludeNodeModules: false, // autoExcludeNodeModules: { enable: true, manualChunks: ['vue'] }, threadPool: false, // threadPool: { enable: true, size: 4 } options: { compact: true, controlFlowFlattening: true, controlFlowFlatteningThreshold: 1, deadCodeInjection: false, debugProtection: true, debugProtectionInterval: 0, disableConsoleOutput: false, identifierNamesGenerator: 'hexadecimal', log: false, numbersToExpressions: false, renameGlobals: false, selfDefending: true, simplify: true, splitStrings: false, stringArray: false, stringArrayCallsTransform: false, stringArrayCallsTransformThreshold: 0.5, stringArrayEncoding: [], stringArrayIndexShift: true, stringArrayRotate: true, stringArrayShuffle: true, stringArrayWrappersCount: 1, stringArrayWrappersChainedCalls: true, stringArrayWrappersParametersMaxCount: 2, stringArrayWrappersType: 'variable', stringArrayThreshold: 0.75, unicodeEscapeSequence: false, } } export default ({mode})=>{ const env = loadEnv(mode, './') // console.log(env) return defineConfig({ plugins: [ // VueDevTools(), vue(), Components({ resolvers: [VantResolver()], }), env.VITE_NODE_ENV==='development' ? null : vitePluginBundleObfuscator(defaultObfuscatorConfig) ], server:{ host: "localhost", port: 8081, proxy: { '/h5Api': {
> 
> ```
>         },
>         }
>     },
>     resolve: {
>     alias: {
>         '@': path.resolve(__dirname, 'src')
>     }
>     },
>     build: {
>     rollupOptions: {
>         output: {
>         chunkFileNames: 'static/js/[name]-[hash].js',
>         entryFileNames: 'static/js/[name]-[hash].js',
>         assetFileNames: 'static/[ext]/[name]-[hash].[ext]',
>         }
>     },
>     minify:'terser',
>     terserOptions: {
>         compress: {
>         drop_console: true,
>         drop_debugger: true,
>         },
>     },
>     },
> })
> ```
> 
> }
> 
> `
> 
> ![screenshot-20241107-172212](https://private-user-images.githubusercontent.com/101165875/383894523-39f03d35-faaf-4528-b5e1-fdc5d334ee3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzE5NTcsIm5iZiI6MTczMDk3MTY1NywicGF0aCI6Ii8xMDExNjU4NzUvMzgzODk0NTIzLTM5ZjAzZDM1LWZhYWYtNDUyOC1iNWUxLWZkYzVkMzM0ZWUzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwOTI3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzkwNzYzZTkwOGQ5NDQxMzY5ZmY2Njg0NmYwNmJiYjYxZDZiNTljZTBmYTA5ODYzM2JmN2FlZDE3Yjk4NDU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lELG2_Z2Bn6Aqiq6-5jMMgTObpnndxsPPgs8Ib8kBUk)

你把autoExcludeNodeModules设置成true，excludes 里的 vue-router 给去了试试。然后这里的判断 env.VITE_NODE_ENV==='development' ? null :
vitePluginBundleObfuscator(defaultObfuscatorConfig) 也不需要。
