### ISSUE TITLE
定时器混淆失败

### ISSUE THREAD

**Issue by han201379873** [z0ffy/vite-plugin-bundle-obfuscator#97]
定时器混淆后不执行了

**Comment by z0ffy** [comment]
> 定时器混淆后不执行了

看下这个例子：https://stackblitz.com/edit/vitejs-vite-ywho91?file=vite.config.js
我这边测试是正常的。如果你那有问题，请提供一些可复现代码。

**Comment by han201379873** [comment]
我使用的不是默认配置。而是自定义配置的

**Comment by z0ffy** [comment]
> 我使用的不是默认配置。而是自定义配置的

配置贴一下

**Comment by han201379873** [comment]
const allObfuscatorConfig = {
  excludes: [],
  enable: true,
  log: true,
  autoExcludeNodeModules: true,
  // autoExcludeNodeModules: { enable: true, manualChunks: ['vue'] }
  threadPool: true,
  // threadPool: { enable: true, size: 4 }
  options: {
    compact: true,
    controlFlowFlattening: true,
    controlFlowFlatteningThreshold: 1,
    deadCodeInjection: false,
    debugProtection: false,
    debugProtectionInterval: 0,
    disableConsoleOutput: false,
    identifierNamesGenerator: 'hexadecimal',
    log: false,
    numbersToExpressions: false,
    renameGlobals: false,
    selfDefending: true,
    simplify: true,
    splitStrings: false,
    stringArray: false,
    stringArrayCallsTransform: false,
    stringArrayCallsTransformThreshold: 0.5,
    stringArrayEncoding: [],
    stringArrayIndexShift: true,
    stringArrayRotate: true,
    stringArrayShuffle: true,
    stringArrayWrappersCount: 1,
    stringArrayWrappersChainedCalls: true,
    stringArrayWrappersParametersMaxCount: 2,
    stringArrayWrappersType: 'variable',
    stringArrayThreshold: 0.75,
    unicodeEscapeSequence: false,
  }
};

**Comment by z0ffy** [comment]
> const allObfuscatorConfig = { excludes: [], enable: true, log: true, autoExcludeNodeModules: true, // autoExcludeNodeModules: { enable: true, manualChunks: ['vue'] } threadPool: true, // threadPool: { enable: true, size: 4 } options: { compact: true, controlFlowFlattening: true, controlFlowFlatteningThreshold: 1, deadCodeInjection: false, debugProtection: false, debugProtectionInterval: 0, disableConsoleOutput: false, identifierNamesGenerator: 'hexadecimal', log: false, numbersToExpressions: false, renameGlobals: false, selfDefending: true, simplify: true, splitStrings: false, stringArray: false, stringArrayCallsTransform: false, stringArrayCallsTransformThreshold: 0.5, stringArrayEncoding: [], stringArrayIndexShift: true, stringArrayRotate: true, stringArrayShuffle: true, stringArrayWrappersCount: 1, stringArrayWrappersChainedCalls: true, stringArrayWrappersParametersMaxCount: 2, stringArrayWrappersType: 'variable', stringArrayThreshold: 0.75, unicodeEscapeSequence: false, } };

https://stackblitz.com/edit/vitejs-vite-ywho91?file=vite.config.js 我这边看还是正常的，你可以看下

**Comment by z0ffy** [comment]
> 难道混淆把这个去掉了么，我如果使用alert是游泳的，但这个就不运行了setInterval(function () { var startTime = performance.now(); // 设置断点 debugger; var endTime = performance.now(); // 设置一个阈值，例如100毫秒 if (endTime - startTime > 100) { window.location.href = "about:blank"; } }, 1000);

![image](https://github.com/user-attachments/assets/1cee9341-35e8-4daf-b613-7dd3a37a2e89)

还是那个连接，用你的代码看着也还是没问题的。

**Comment by han201379873** [comment]
![image](https://github.com/user-attachments/assets/44f47aba-e29a-45fd-9061-ee9fe63ea743)
我这边编译后就是没，有没有可能是其他配置影响了

**Comment by han201379873** [comment]
![image](https://github.com/user-attachments/assets/20d67ab2-6300-40a9-91a0-7877e23f865d)
有些神奇

**Comment by han201379873** [comment]
![image](https://github.com/user-attachments/assets/3737b318-5a38-4586-b469-8a9afc804583)
抱歉，我的原因，有其他插件去除了debugger

**Comment by z0ffy** [comment]
> ![image](https://private-user-images.githubusercontent.com/52527278/389854673-3737b318-5a38-4586-b469-8a9afc804583.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDk0NjUsIm5iZiI6MTczMjYwOTE2NSwicGF0aCI6Ii81MjUyNzI3OC8zODk4NTQ2NzMtMzczN2IzMTgtNWEzOC00NTg2LWI0NjktOGE5YWZjODA0NTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA4MTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZDc3NTUwYTJjYWFhNmU5YzdmZmYxMGQ2OTY0NWMwMWU5MzQwYTI0MTAzOGEwNWFkZmVhYmQxOGVkZDc2YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kQW4kzXfyv3MjMAn6A3ZrakSctxw7HWHh0tY2ry1ELI) 抱歉，我的原因，有其他插件去除了debugger

好的，如果没其他问题，issue我就关闭了。喜欢这个插件的话可以点个star，会不定期更新
