### ISSUE TITLE
应该增加一个回调方法来控制文件是否加密

### ISSUE THREAD

**Issue by 005001** [z0ffy/vite-plugin-bundle-obfuscator#98]
excludes排除选项也不好控制
现在用到的名字是编译后的名字,而不是原始名字
为了防止通过js名字猜测功能, 利用 chunkFileNames 生成的随机名字是 hash 的文件名
每次编译文件名都不一样, 而且没有固定特征例如下面的
DvWlF_rV.js
KhGgKple.js
IicgbkIM.js
希望增加一个回调方法来控制文件是否加密, 文件名最好是原始的名字

**Comment by z0ffy** [comment]
> excludes排除选项也不好控制 现在用到的名字是编译后的名字,而不是原始名字 为了防止通过js名字猜测功能, 利用 chunkFileNames 生成的随机名字是 hash 的文件名 每次编译文件名都不一样, 而且没有固定特征例如下面的 DvWlF_rV.js KhGgKple.js IicgbkIM.js 希望增加一个回调方法来控制文件是否加密, 文件名最好是原始的名字

能不能把你的vite配置贴一下看看。然后想了解一下什么文件为什么需要忽略混淆。

**Comment by z0ffy** [comment]
> 入口的 app.vue 只有登录的功能(所以index.js文件比较小,可以上高强度的混淆), 然后根据用户登录的类型动态显示一些组件, 比如管理员能显示后台, 通过混淆 让用户不能看到全部的js路径, 而其他组件的js则不需要混淆了, 因为登录的用户类型不对那些js组件就不会加载, 他不知道路径也就没必要混淆了,
> 
> output.entryFileNames = (entryInfo) => { return 'main_[hash].js'; } output.chunkFileNames = (chunkInfo) => { return '[hash].js'; } output.assetFileNames = (assetInfo) => { return '[hash][extname]'; } 并通过钩子将文件名全部随机, 以前用的是 vite-plugin-obfuscator, 配置如下 exclude: [], include: ['src/App.vue'], // , 'path/anyjs/**/*.js', /foo.js$/ global: false, 他有包括和例外两个参数,并且能以源文件名的方式跳过混淆, 而 vite-plugin-bundle-obfuscator 是以编译后的名称判断的,,,,,

根据你说的情况，目前只能建议你两个方案：
1、全部混淆。（开启多线程之后速度也还可以接受）
2、针对不需要混淆的文件进行单独分包，自定义name，然后设置exclude。

**Comment by z0ffy** [comment]
> > 根据你说的情况，目前只能建议你两个方案： 1、全部混淆。（开启多线程之后速度也还可以接受） 2、针对不需要混淆的文件进行单独分包，自定义name，然后设置exclude。
> > 嗯 目前我只能将index.js 指定一个名字, 然后用正则排除其他js
> > excludes: [/^(?!._main_._).*$/],
> > 这样就能只混淆main.js了, 暂时只能这样了

我其实倒是建议你除 node_modules 之外全部混淆。
